name: example
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.3.0-0 <4.0.0'

dependencies:
  async: ^2.11.0
  collection: ^1.18.0
  meta: ^1.11.0

dev_dependencies:
  checks: ^0.2.2
  # funny_lints:
  #   path: ../funny_lints
  logging: ^1.2.0
  test: ^1.24.0
